### ISSUE TITLE
GKE cluster version error

### ISSUE THREAD

**Issue by phriscage** [mukundha/hipster-apim-demo#5]
## Issue/Request:
GKE cluster version error when specifying a version patch suffix:

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Master version "1.11.2-gke.9" is unsupported.
```

I would recommend using just `major.minor` I.E. `11.1`

**Comment by mukundha** [comment]
yes, good point, is there a way to force GKE to deploy always the latest version?

**Comment by phriscage** [comment]
I think it's safe to remove the _--cluster-version_ and let GKE default to the latest version for the region on the master/node

**Comment by mukundha** [comment]
I tried that before, but the default was an older stable version (think it
was 1.9), but istio required 1.10 - let me check if that has changed
